name: '@srclaunch/web-environment'
description: Web environment specific utilities for SrcLaunch applications
author: Steven Bennett <steven@srclaunch.com>
license: MIT
version: 0.1.26
engines:
  node: '>=16'
  yarn: '>=3.2.0'
publishConfig:
  access: public
  registry: https://registry.npmjs.org/
type: module
main: ./dist/index.mjs
types: ./dist/index.d.ts
files:
  - package.json
  - dist
module: ./dist/index.mjs
exports:
  .:
    import: ./dist/index.mjs
    require: ./dist/index.umd.cjs
scripts:
  yui: yarn upgrade-interactive
  qr: >-
    yarn srclaunch changesets add --message "Quick release" && yarn srclaunch
    release --push
  build: yarn srclaunch build
  test: yarn srclaunch test
  test:watch: yarn srclaunch test --watch
  test:coverage: yarn srclaunch test --coverage
  release: yarn srclaunch release
devDependencies:
  '@types/node': 17.0.31
  ava: 4.2.0
  '@microsoft/eslint-plugin-sdl': 0.2.0
  eslint: 8.14.0
  eslint-import-resolver-typescript: 2.7.1
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-functional: 4.2.1
  eslint-plugin-import: 2.26.0
  eslint-plugin-node: 11.1.0
  eslint-plugin-only-warn: 1.0.3
  eslint-plugin-regexp: 1.7.0
  eslint-plugin-simple-import-sort: 7.0.0
  eslint-plugin-sort-keys-fix: 1.1.2
  eslint-plugin-sort-requires: 2.1.0
  eslint-plugin-unicorn: 42.0.0
  eslint-config-prettier: 8.5.0
  eslint-plugin-prettier: 4.0.0
  prettier: 2.6.2
  standard-version: 9.3.2
  '@srclaunch/cli': 0.1.461
  '@srclaunch/dx': 0.1.52
  '@srclaunch/types': 0.1.151
  eslint-config-stylelint: 15.1.0
  stylelint: 14.8.2
  stylelint-config-idiomatic-order: 8.1.0
  stylelint-config-prettier: 9.0.3
  stylelint-config-recommended: 7.0.0
  stylelint-order: 5.0.0
  c8: 7.11.2
  '@typescript-eslint/eslint-plugin': 5.22.0
  '@typescript-eslint/parser': 5.22.0
  typescript: 4.6.4
