name: Deploy package
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    if: github.repository_owner == 'srclaunch'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Run tests script
        run: yarn test
        
  package:
    name: Deploy package
    runs-on: ubuntu-latest
    if: github.repository_owner == 'srclaunch'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Enable corepack
        run: corepack enable

      - name: Enable Yarn Berry
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Allow private package registry access
        id: allow-private-package-registry-access
        run: |
          echo "npmScopes:" > ./.yarnrc.yml
          echo "  ${{ github.event.repository.owner.login }}:" >> ./.yarnrc.yml
          echo "    npmRegistryServer: https://registry.npmjs.org" >> ./.yarnrc.yml
          echo "    npmAlwaysAuth: true" >> ./.yarnrc.yml
          echo "    npmAuthToken: ${{ secrets.NPM_ACCESS_TOKEN }}" >> ./.yarnrc.yml

      - name: Publish package to NPM
        run: yarn npm publish
