name: Deploy package
on:
  push:
    branches:
      - main
jobs:
  package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'srclaunch'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          # always-auth: true
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@srclaunch'
      - run: yarn install
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

# name: Deploy package
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-18.04]
#         node-version: [12.x, 14.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js 14.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.x
#           registry-url: https://npm.pkg.github.com/
#           scope: '@srclaunch'
#       - name: show npmrc
#         run: cat .npmrc
#       - run: npm ci
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
#       - run: npm run build

#   package:
#     needs: [build]
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js 14.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.x
#           registry-url: https://npm.pkg.github.com/
#           scope: '@srclaunch'
#       # - run: echo "registry=https://npm.pkg.github.com/@srclaunch\n//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
#       - name: show npmrc
#         run: cat .npmrc
#       - run: npm ci
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
#       - run: npm run build
#       - run: npm pack
#       - name: Upload build artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: package
#           path: '*.tgz'

#   publish:
#     name: 'Publish to GitHub Packages'
#     needs: [package]
#     runs-on: ubuntu-18.04
#     if: github.repository_owner == 'srclaunch' # && github.token != ''
#     steps:
#       - name: Download build artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: package
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 14.x
#           registry-url: https://npm.pkg.github.com/
#           scope: '@srclaunch'
#       - run: echo "registry=https://npm.pkg.github.com/@srclaunch" >> .npmrc
#       - run: npm publish $(ls *.tgz)
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
